using System;
using System.Runtime.InteropServices;

namespace NoteHighlightAddin.Highlighting.KeywordGroups.Services
{
    /// <summary>
    /// Generates temporary .lang files used by the highlight preview.
    /// </summary>
    [ComVisible(false)] 
    public interface IHighlightPreviewLanguageService
        : IDisposable
    {
        /// <summary>
        /// Creates a temporary .lang file from the current editable
        /// configuration and returns its complete path.
        /// </summary>
        string GeneratePreviewLanguage(
            EditableLanguageConfiguration configuration);

        /// <summary>
        /// Removes temporary preview language files generated by this service.
        /// </summary>
        void Cleanup();
    }
}