using GenerateHighlightContent;
using NoteHighlightAddin.Highlighting.KeywordGroups;
using System;
using System.Runtime.InteropServices;

namespace NoteHighlightAddin.Highlighting.Preview.Services
{
    /// <summary>
    /// Generates temporary HTML previews using an editable
    /// language configuration.
    /// </summary>
    /// 
    [ComVisible(false)]
    public interface IPreviewHtmlService : IDisposable
    {
        /// <summary>
        /// Generates a temporary HTML preview and returns
        /// its complete path.
        /// </summary>
        string GeneratePreviewHtml(
            EditableLanguageConfiguration configuration,
            HighLightParameter parameter);

        /// <summary>
        /// Removes temporary files generated by the service.
        /// </summary>
        void Cleanup();
    }
}